/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-92779-g8b53d13-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
